# Adds the "Sponsor" button to the repo header and the sponsor link on issues/PRs.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [murugu-21]
